[package]
name = "demo-share"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
use-std = []
# mutually exclusive
ex-a = []
ex-b = []
