[package]
name = "host-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.demo-share]
path = "../../shared/demo-share"
features = ["use-std"]
